### ISSUE TITLE
Handover of systemd's socket into the server does not work

### ISSUE THREAD

**Issue by mariospr** [Spindel/systemd-socketactivation#1]
Setting the HTTPServer's socket to the one received from systemd needs to happen after initializing the SockInheritHTTPServerinstance, not before, or nothing will work as a new socket will get created listening in a random port (as the intented one is already in use by systemd).

**Comment by mariospr** [comment]
See the patch attached in the PR, please review, thanks!

**Comment by Spindel** [comment]
Thank you, but I'm not sure if I completely understand _where_ you are seeing this problem, I'll comment further in the PR.

**Comment by Spindel** [comment]
And with some more coffee I completely see the issue!  Thank you, merged the fix.

Have a great week!

**Comment by mariospr** [comment]
Coffee is important :). Thanks for merging this, and thanks for the nice project in the first place. Very useful to understand how systemd socket-activation works in an easy way.

**Comment by Spindel** [comment]
Indeed. I should probably tear out a few other of my simple "this is how
you do it" into projects like this.

Thanks again for the good catch. I can imagine that it was a bit
frustrating to find it.

**Comment by mariospr** [comment]
No problem. Happy to help!
